/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mentorshipContractSol from "./MentorshipContract.sol";
export type { mentorshipContractSol };
export type { EduToken } from "./EduToken";
export type { MentorshipNFT } from "./MentorshipNFT";
